### ISSUE TITLE
zoom in throws a StackOverflowException

### ISSUE THREAD

**Issue by mogikanin** [DotSpatial/DotSpatial#776]
**This issue was imported from [CodePlex](http://dotspatial.codeplex.com/workitem/63625)**

**[aapnoot1](http://www.codeplex.com/site/users/view/aapnoot1)** wrote 2016-04-12 at 15:37
When zooming in to an extent of less then 1e-7 in OnViewExtentsChanged of DotSpatial.Controls.Map, the ViewExtender will be caught in a infinite loop and will eventually throw a StockOverflowException.

This was achieved by scrolling in a couple of times on a shape. 

Attached are the ViewExtents' values during the infinite loop. 

Please have a look at this. 

Cheers

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2016-04-12 at 21:17
What DotSpatial version do you use?

I'm running the latest changeset.

You said you scrolled in on a shape when your error showed up. So I went and scrolled in on my map til I had an extent smaller than 1e-7 and then scrolled in another 1000 times by keeping the + key pressed. This runs the code shown in your screenshot without
 causing an error.

If you're not running the latest changeset please download that and try whether you get your error again.

If you're running the lastest changeset please tell me how to recreate your error.

**[aapnoot1](http://www.codeplex.com/site/users/view/aapnoot1)** wrote 2016-04-13 at 13:09
Hi and thanks for your quick reply. 

I used the latest source code available on your website (also reproducible when using the compiled download).

Attached is the callstack. 

Also, when limiting the zoom from <strong>1e-7</strong> to <strong>1e-4</strong> in
<strong>DotSpatial.Controls.Map.OnViewExtentsChanged</strong>, there is no StackOverflowException.

**[aapnoot1](http://www.codeplex.com/site/users/view/aapnoot1)** wrote 2016-04-13 at 14:21
Attached is a proposed solution and a test case

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2016-04-14 at 14:24
Your solution was an interesting way of telling the code to go to hell. Asking the newExtent whether it is 1e-7 away from the oldExtent always results in false if you create the newExtent by removing 1e-7/2 from the oldExtent. It would have been easier
 if you'd simply removed the old code. ;)

The test case you added worked for me in combination with the old code without causing an error.

But here comes the good part.

I took the center of your pictures ViewExtent in combination with the callstack and used this to have a look at the function and came to the following problem.

When ViewExtent gets set, somewhere down the line MapFrame.ResetAspectRatio is called. This tries to match ViewExtent to the proportions of the Map. Under certain conditions ResetAspectRatio makes the width/height of the ViewExtent smaller than 1e-7 which results
 in OnViewExtentsChanged trying to reset it to 1e-7 and then everything begins again.

So I added some code to OnViewExtentsChanged that stops setting ViewExtent to minExt if the last set ViewExtent was minExt.

This should keep the code from going into the loop.

So please download the latest changeset and check whether this works for you.

**[aapnoot1](http://www.codeplex.com/site/users/view/aapnoot1)** wrote 2016-04-14 at 15:19
You are correct. I shouldn't have called it 'proposed solution', but 'implementation that worked for our upcoming release'. :)

We found out it had to do with double imprecision, which fell through the if-statement, causing the infinite loop.

We ended up using the following:

if (ViewExtents.Width < minExt || ViewExtents.Height < minExt)

{

<pre><code>var x = ViewExtents.Center.X;
var y = ViewExtents.Center.Y;
ViewExtents.SetCenter(x, y, minExt, minExt);
return;</code></pre>
}

This will prevent a new ExtentsChanged event, but might corrupt the aspect ratio you mentioned.

I will test your solution as soon as I can. Thanks!

**[jany_](http://www.codeplex.com/site/users/view/jany_)** wrote 2016-04-22 at 13:06
Did you have time to check whether the fix works for you?

I'd like to close this issue.

**Comment by jany-tenaj** [comment]
This was fixed in 1.9. As the user didn't react I'll assume the fix works as expected.

**Comment by DavisMillier** [comment]
It seems not fixed , i get this error on zoom in !
May you check Dotspatial V2 ?
